const KEY="mastro_shayen_magazzino_v1";
let data=JSON.parse(localStorage.getItem(KEY)||'{"items":[],"recipes":[]}');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cats=[["Malti","🌾"],["Luppoli","🌿"],["Lieviti","🧫"],["Additivi","🧪"]];
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2400)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function openModal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden");document.body.style.overflow="hidden";bindSwipeDelete()}
function closeModal(){$("#modal").classList.add("hidden");document.body.style.overflow=""}
$("#modalClose").onclick=closeModal;
function showView(v){$$('.view').forEach(x=>x.classList.remove('active'));$("#"+v).classList.add('active');$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo(0,0)}
$$('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$("#settingsBtn").onclick=()=>showView("settings");
$("#closeSettings").onclick=()=>showView("dashboard");
function dateState(d){if(!d)return"";const now=new Date(),x=new Date(d+"T23:59:59"),days=(x-now)/86400000;if(days<0)return"expired";if(days<=30)return"warning";return""}
function grouped(){const map={};data.items.forEach((i,idx)=>{const key=(i.category+"|"+String(i.name||'').trim()).toLowerCase();if(!map[key])map[key]={name:String(i.name||'').trim(),category:i.category,total:0,unit:i.unit,lots:[]};map[key].total+=Number(i.qty)||0;map[key].lots.push({...i,__index:idx})});return Object.values(map)}
function renderDashboard(){renderInventory()}
function renderInventory(){
 const q=$("#inventorySearch").value.toLowerCase();const c=$("#categoryFilter").value;
 const groups=grouped().filter(g=>(!q||g.name.toLowerCase().includes(q))&&(!c||g.category===c));
 if(!groups.length){$("#inventoryList").innerHTML='<div class="empty">Nessun materiale trovato.</div>';return}
 const order=["Malti","Luppoli","Lieviti","Additivi"];
 if(!c){$("#inventoryList").innerHTML=order.map(category=>{const items=groups.filter(g=>g.category===category);if(!items.length)return"";return `<section class="inventory-section"><h2 class="inventory-section-title">${category}</h2><div class="inventory-section-list">${items.map(g=>inventoryGroupHTML(g)).join("")}</div></section>`}).join("")}else $("#inventoryList").innerHTML=groups.map(g=>inventoryGroupHTML(g)).join("");
 $$(".inventory-clickable").forEach(el=>{let sx=0, moved=false;el.onclick=()=>{if(!moved)editGroup(decodeURIComponent(el.dataset.name),el.dataset.category);moved=false};el.addEventListener('touchstart',e=>{sx=e.touches[0].clientX;moved=false},{passive:true});el.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(dx<-70){moved=true;el.classList.add('swiped');}else if(dx>30){moved=true;el.classList.remove('swiped');}},{passive:true});el.querySelector('.inventory-delete').onclick=e=>{e.stopPropagation();const n=decodeURIComponent(el.dataset.name),cat=el.dataset.category;if(confirm('Rimuovi dal magazzino?')){data.items=data.items.filter(i=>!(i.category===cat&&String(i.name||'').trim().toLowerCase()===n.trim().toLowerCase()));save();toast('Articolo rimosso')}}});
}
function inventoryGroupHTML(g){
 return `<div class="item inventory-clickable" data-name="${encodeURIComponent(g.name)}" data-category="${esc(g.category)}" role="button" tabindex="0"><div class="item-main"><strong>${esc(g.name)} — ${g.total} ${esc(g.unit||g.lots[0]?.unit||"")}</strong><small>${esc(g.category)} · ${g.lots.length} lotto${g.lots.length===1?'':'i'}</small><details onclick="event.stopPropagation()"><summary>Dettaglio lotti</summary><div class="lot-details">${g.lots.map(l=>`<div>${esc(l.name)} ${esc(l.expiry||"Nessuna scadenza")} — <b>${l.qty} ${esc(l.unit)}</b> ${dateState(l.expiry)==="expired"?'<span class="expired">SCADUTO</span>':dateState(l.expiry)==="warning"?'<span class="warning">IN SCADENZA</span>':""}</div>`).join("")}</div></details></div><button type="button" class="inventory-delete" aria-label="Rimuovi">×</button></div>`;
}
function editGroup(name,category){
 const idxs=data.items.map((x,i)=>({x,i})).filter(o=>o.x.category===category&&String(o.x.name||'').trim().toLowerCase()===name.trim().toLowerCase()).map(o=>o.i);
 if(!idxs.length)return;
 openModal(`<form id="itemEditor" class="form"><h2>Gestisci ${esc(name)}</h2><label>Nome materiale<input name="name" value="${esc(data.items[idxs[0]].name)}" required></label><label>Categoria<select name="category">${["Malti","Luppoli","Lieviti","Additivi"].map(c=>`<option ${c===category?'selected':''}>${c}</option>`).join('')}</select></label><div id="lotEditorList" class="lot-editor-list">${idxs.map((i,n)=>lotEditorRow(data.items[i],n)).join('')}</div><button type="button" class="secondary" id="addLotEdit">＋ Aggiungi lotto</button><div class="editor-actions"><button type="button" class="danger" id="deleteItem">🗑 Rimuovi dal magazzino</button><button class="primary">Salva modifiche</button></div></form>`);
 $("#addLotEdit").onclick=()=>{$("#lotEditorList").insertAdjacentHTML('beforeend',lotEditorRow({name:name,category:category,qty:0,unit:data.items[idxs[0]].unit||'kg',expiry:''},$$('.lot-editor-row').length))};
 $("#itemEditor").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),newName=fd.get('name').trim(),newCat=fd.get('category');const rows=$$('.lot-editor-row');const replacement=rows.map((row,n)=>({name:newName,category:newCat,qty:Number(row.querySelector('[name="qty"]').value)||0,unit:row.querySelector('[name="unit"]').value,expiry:row.querySelector('[name="expiry"]').value||''}));idxs.sort((a,b)=>b-a).forEach(i=>data.items.splice(i,1));data.items.push(...replacement);save();closeModal();toast('Articolo aggiornato')};
 $("#deleteItem").onclick=()=>{if(confirm('Rimuovi dal magazzino?')){idxs.sort((a,b)=>b-a).forEach(i=>data.items.splice(i,1));save();closeModal();toast('Articolo rimosso')}};
}
function lotEditorRow(l,n){return `<div class="lot-editor-row swipe-delete"><label>Quantità<input name="qty" type="number" step="any" value="${esc(l.qty)}"></label><label>Unità<select name="unit">${['kg','g','L','ml','pz'].map(u=>`<option ${u===l.unit?'selected':''}>${u}</option>`).join('')}</select></label><label>Scadenza<input name="expiry" type="date" value="${esc(l.expiry||'')}"></label><button type="button" class="row-delete" aria-label="Rimuovi lotto">×</button></div>`}
function bindSwipeDelete(){ $$('.swipe-delete').forEach(row=>{let sx=0;row.addEventListener('touchstart',e=>{sx=e.touches[0].clientX},{passive:true});row.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(dx<-70)row.classList.add('swiped');else if(dx>30)row.classList.remove('swiped')},{passive:true});row.querySelector('.row-delete')?.addEventListener('click',()=>{if(confirm('Rimuovi questo lotto?'))row.remove()})}) }
$("#inventorySearch").oninput=renderInventory;$("#categoryFilter").onchange=renderInventory;
$("#addProduct").onclick=()=>openModal(`<form id="addItemForm" class="form"><h2>Aggiungi materiale</h2><label>Nome materiale<input name="name" required placeholder="es. Maris Otter"></label><label>Categoria<select name="category"><option>Malti</option><option>Luppoli</option><option>Lieviti</option><option>Additivi</option></select></label><div class="form-grid"><label>Quantità<input name="qty" type="number" step="any" required></label><label>Unità<select name="unit"><option>kg</option><option>g</option><option>L</option><option>ml</option><option>pz</option></select></label></div><label>Scadenza<input name="expiry" type="date"></label><div class="editor-actions"><button class="primary">Aggiungi al magazzino</button></div></form>`);
$(document).on('submit','#addItemForm',e=>{e.preventDefault();const f=new FormData(e.target);data.items.push({name:f.get('name').trim(),category:f.get('category'),qty:Number(f.get('qty'))||0,unit:f.get('unit'),expiry:f.get('expiry')||''});save();closeModal();toast('Materiale aggiunto')});
function creatorAnalysis(){const totals={};grouped().forEach(g=>totals[g.category]=(totals[g.category]||0)+g.total);const maltKg=(totals.Malti||0);const hopsG=(totals.Luppoli||0);const yeast=(totals.Lieviti||0);const litresByMalt=maltKg>0?Math.floor((maltKg/0.22)*10)/10:0;const litresByHops=hopsG>0?Math.floor((hopsG/5))*1:0;const litres=Math.max(0,Math.min(litresByMalt||999,litresByHops||999));let suggestions=[];if(litres>0&&yeast>0)suggestions=[['Pale Ale',litres,'Malti + Luppoli + Lievito disponibili'],['IPA',Math.max(0,Math.floor(litres*0.75*10)/10),'Richiede una maggiore dotazione di luppolo'],['Session Ale',Math.max(0,Math.floor(litres*1.2*10)/10),'Stima più conservativa di densità']];else suggestions=[['Analisi incompleta',0,'Servono almeno malti, luppoli e lievito nel magazzino']];return suggestions}
function renderCreator(){const out=$("#creatorResult");if(!out)return;const s=creatorAnalysis();out.innerHTML=s.map(x=>`<article class="creator-card"><div><strong>${x[0]}</strong><small>${esc(x[2])}</small></div><b>${x[1]} L</b></article>`).join('')}
$("#creatorAnalyze").onclick=renderCreator;
$("#creatorQuestion").onsubmit=e=>{e.preventDefault();const q=$("#creatorInput").value.trim();if(!q)return;const a=creatorAnalysis();$("#creatorChat").insertAdjacentHTML('beforeend',`<div class="chat-user">${esc(q)}</div><div class="chat-ai">In questa versione Creator usa i dati del magazzino per l'analisi locale. Posso indicarti le produzioni stimate disponibili: ${a.map(x=>`${x[0]} ${x[1]} L`).join(', ')}. Per una vera conversazione AI generativa servirà collegare un modello tramite backend/API.</div>`);$("#creatorInput").value=''};
function renderRecipes(){const el=$("#recipeList");if(!el)return;el.innerHTML=data.recipes.length?data.recipes.map(r=>`<article class="recipe-card"><div class="recipe-title">${esc(r.name)}</div></article>`).join(''):'<div class="empty">Nessuna ricetta.</div>'}
$("#newRecipe")?.addEventListener('click',()=>toast('Editor ricette da mantenere nella prossima revisione'));
$("#backupBtn").onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mastro_shayen_backup.json';a.click();URL.revokeObjectURL(a.href)};
$("#restoreFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(!x.items||!x.recipes)throw 0;if(confirm('Sostituire i dati attuali con il backup?')){data=x;save();toast('Backup caricato')}}catch{alert('Backup non valido')}};rd.readAsText(f)};
$$('[data-reset]').forEach(b=>b.onclick=()=>{const c=b.dataset.reset;if(confirm('Reset del reparto '+c+'?')){data.items=data.items.filter(i=>i.category!==c);save();toast('Reparto resettato')}});
$("#resetAll").onclick=()=>{if(confirm('ATTENZIONE: eliminare TUTTO il magazzino e tutte le ricette?')){data={items:[],recipes:[]};save();toast('Dati azzerati')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
renderAll();function renderAll(){renderDashboard();renderRecipes();renderCreator()}
