const KEY="mastro_shayen_magazzino_v1";
let data=JSON.parse(localStorage.getItem(KEY)||'{"items":[],"recipes":[]}');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function openModal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
$("#modalClose").onclick=closeModal;
$("#menuBtn").onclick=()=>{$("#drawer").classList.add("open");$("#backdrop").classList.add("open")};
$("#closeMenu").onclick=$("#backdrop").onclick=()=>{$("#drawer").classList.remove("open");$("#backdrop").classList.remove("open")};
$$(".drawer nav button").forEach(b=>b.onclick=()=>{showView(b.dataset.view);$("#closeMenu").click()});
function showView(v){$$(".view").forEach(x=>x.classList.remove("active"));$("#"+v).classList.add("active");window.scrollTo(0,0)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function dateState(d){if(!d)return"";const now=new Date(), x=new Date(d+"T23:59:59");const days=(x-now)/86400000;if(days<0)return"expired";if(days<=30)return"warning";return""}
function grouped(){const map={};data.items.forEach(i=>{const k=i.name.trim().toLowerCase();if(!map[k])map[k]={name:i.name,category:i.category,total:0,lots:[]};map[k].total+=Number(i.qty)||0;map[k].lots.push(i)});return Object.values(map)}
function renderDashboard(){renderInventory()}
function renderInventory(){let q=$("#inventorySearch").value.toLowerCase(),c=$("#categoryFilter").value;let groups=grouped().filter(g=>(!q||g.name.toLowerCase().includes(q))&&(!c||g.category===c));$("#inventoryList").innerHTML=groups.length?groups.map((g,n)=>`<div class="item"><div class="item-main"><strong>${esc(g.name)} — ${g.total} ${esc(g.lots[0].unit)}</strong><small>${esc(g.category)}</small><details><summary>Dettaglio lotti</summary><div class="lot-details">${g.lots.map(l=>`<div>${esc(l.name)} ${esc(l.expiry||"senza scadenza")} — <b>${l.qty} ${esc(l.unit)}</b> ${dateState(l.expiry)==="expired"?'<span class="expired">SCADUTO</span>':dateState(l.expiry)==="warning"?'<span class="warning">IN SCADENZA</span>':""}</div>`).join("")}</div></details></div><button class="secondary" onclick="editGroup('${encodeURIComponent(g.name)}')">Gestisci</button></div>`).join(""):'<div class="empty">Nessun materiale trovato.</div>'}
function renderRecipes(){$("#recipeList").innerHTML=data.recipes.length?data.recipes.map(r=>`<article class="recipe-card">${r.image?`<img src="${r.image}" alt="">`:""}<h3>${esc(r.name)}</h3><p class="muted">${esc(r.style||"")}</p>${r.ingredients.map(i=>`<div class="ingredient">${esc(i.category)} · ${esc(i.name)} — <b>${i.qty} ${esc(i.unit)}</b></div>`).join("")}<button class="primary scale-btn" data-id="${r.id}" style="margin-top:14px;width:100%">⬇ Scala dal magazzino</button><button class="secondary" data-edit="${r.id}" style="margin-top:7px;width:100%">Modifica</button></article>`).join(""):'<div class="empty">Nessuna ricetta. Creane una con il pulsante ＋ Ricetta.</div>';$$(".scale-btn").forEach(b=>b.onclick=()=>scaleRecipe(b.dataset.id));$$("[data-edit]").forEach(b=>b.onclick=()=>editRecipe(b.dataset.edit))}
function renderAll(){renderDashboard();renderInventory();renderRecipes()}
["input","change"].forEach(ev=>{$("#inventorySearch").addEventListener(ev,renderInventory);$("#categoryFilter").addEventListener(ev,renderInventory)});
$$(".cat").forEach(b=>b.onclick=()=>{$("#categoryFilter").value=b.dataset.category;showView("inventory");renderInventory()});
function addProductForm(existingName="",existingCat="Malti"){openModal(`<form class="form" id="productForm"><h2>＋ Aggiungi materiale</h2><div class="form-grid"><label>Materiale<input name="name" required value="${esc(existingName)}" placeholder="es. Citra"></label><label>Reparto<select name="category"><option ${existingCat==="Malti"?"selected":""}>Malti</option><option ${existingCat==="Luppoli"?"selected":""}>Luppoli</option><option ${existingCat==="Lieviti"?"selected":""}>Lieviti</option><option ${existingCat==="Additivi"?"selected":""}>Additivi</option></select></label><label>Quantità<input name="qty" type="number" min="0" step="0.01" required></label><label>Unità<select name="unit"><option>g</option><option>kg</option><option>bustine</option><option>pz</option><option>ml</option><option>l</option></select></label><label>Scadenza<input name="expiry" type="date"></label><label>Scorta minima<input name="min" type="number" min="0" step="0.01" value="0"></label></div><button class="primary">Salva nel magazzino</button></form>`);$("#productForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.items.push({id:crypto.randomUUID(),name:f.get("name").trim(),category:f.get("category"),qty:Number(f.get("qty")),unit:f.get("unit"),expiry:f.get("expiry"),min:Number(f.get("min")||0)});closeModal();save();toast("Materiale aggiunto")}}
function editGroup(enc){const name=decodeURIComponent(enc);const lots=data.items.filter(i=>i.name.toLowerCase()===name.toLowerCase());openModal(`<div class="form"><h2>${esc(lots[0].name)}</h2>${lots.map(l=>`<div class="item"><div class="item-main"><strong>${l.qty} ${esc(l.unit)}</strong><small>${esc(l.expiry||"Nessuna scadenza")} ${dateState(l.expiry)==="expired"?'<span class="expired">· SCADUTO</span>':""}</small></div><button class="danger" onclick="deleteLot('${l.id}')">Elimina</button></div>`).join("")}<button class="primary" onclick="closeModal();addProductForm('${esc(lots[0].name)}','${lots[0].category}')">＋ Aggiungi altro lotto</button></div>`)}
function deleteLot(id){if(confirm("Eliminare questo lotto?")){data.items=data.items.filter(i=>i.id!==id);save();closeModal();toast("Lotto eliminato")}}
$("#addProduct").onclick=$("#addProduct2").onclick=()=>addProductForm();
function recipeForm(r=null){const ing=r?.ingredients||[];openModal(`<form class="form" id="recipeForm"><h2>${r?"Modifica ricetta":"＋ Nuova ricetta"}</h2><label>Nome ricetta<input name="name" required value="${esc(r?.name||"")}"></label><label>Stile (facoltativo)<input name="style" value="${esc(r?.style||"")}"></label><label>Etichetta PNG/JPG (facoltativa)<input type="file" name="image" accept="image/png,image/jpeg"></label><h3>Materie prime</h3><div id="ingredients">${ing.map((x,i)=>ingredientRow(x,i)).join("")}</div><button type="button" class="secondary" id="addIng">＋ Aggiungi materia prima</button><button class="primary">Salva ricetta</button></form>`);let count=ing.length;$("#addIng").onclick=()=>{$("#ingredients").insertAdjacentHTML("beforeend",ingredientRow({},count++));bindRemove()};bindRemove();$("#recipeForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);let image=r?.image||"";const file=f.get("image");if(file&&file.size)image=await new Promise(res=>{const rd=new FileReader();rd.onload=()=>res(rd.result);rd.readAsDataURL(file)});const ingredients=[...document.querySelectorAll(".ingredient-row")].map(row=>({category:row.querySelector(".icat").value,name:row.querySelector(".iname").value.trim(),qty:Number(row.querySelector(".iqty").value),unit:row.querySelector(".iunit").value})).filter(x=>x.name&&x.qty>0);const obj={id:r?.id||crypto.randomUUID(),name:f.get("name").trim(),style:f.get("style").trim(),image,ingredients,scaled:r?.scaled||false};if(r){data.recipes=data.recipes.map(x=>x.id===r.id?obj:x)}else data.recipes.push(obj);closeModal();save();toast("Ricetta salvata")}}
function ingredientRow(x={},i){return `<div class="ingredient-row"><select class="icat"><option ${x.category==="Malti"?"selected":""}>Malti</option><option ${x.category==="Luppoli"?"selected":""}>Luppoli</option><option ${x.category==="Lieviti"?"selected":""}>Lieviti</option><option ${x.category==="Additivi"?"selected":""}>Additivi</option></select><input class="iname" list="materials" placeholder="Materiale" value="${esc(x.name||"")}" required><input class="iqty" type="number" min="0" step="0.01" placeholder="Qtà" value="${x.qty||""}" required><select class="iunit"><option>g</option><option>kg</option><option>bustine</option><option>pz</option><option>ml</option><option>l</option></select><button type="button" class="danger remove-ing">×</button></div>`}
function bindRemove(){$$(".remove-ing").forEach(b=>b.onclick=()=>b.parentElement.remove())}
$("#newRecipe").onclick=()=>recipeForm();window.editRecipe=id=>recipeForm(data.recipes.find(r=>r.id===id));
async function scaleRecipe(id){const r=data.recipes.find(x=>x.id===id);if(!r)return;if(r.scaled&&!confirm("Hai già scalato dal magazzino, vuoi scalare NUOVAMENTE?"))return;let groups=grouped(), plan=[], problems=[];for(const ing of r.ingredients){let lots=data.items.filter(x=>x.name.toLowerCase()===ing.name.toLowerCase()&&x.category===ing.category&&x.unit===ing.unit).sort((a,b)=>(a.expiry||"9999").localeCompare(b.expiry||"9999"));let total=lots.reduce((s,x)=>s+Number(x.qty),0);if(total<ing.qty)problems.push(`${ing.name}: richiesti ${ing.qty}${ing.unit}, disponibili ${total}${ing.unit}`);else plan.push({ing,lots})}if(problems.length){alert("Materiale insufficiente:\\n\\n"+problems.join("\\n")+"\\n\\nNessuna quantità è stata modificata.");return}let preview=plan.map(p=>{let need=p.ing.qty, lines=[];for(const l of p.lots){if(need<=0)break;let take=Math.min(need,Number(l.qty));lines.push(`${l.name} (${l.expiry||"senza scadenza"}) → ${take}${l.unit}`);need-=take}return `${p.ing.name}:\\n  ${lines.join("\\n  ")}`}).join("\\n\\n");if(!confirm("Confermi la scalatura?\\n\\n"+preview))return;for(const p of plan){let need=p.ing.qty;for(const l of p.lots){if(need<=0)break;let take=Math.min(need,Number(l.qty));l.qty-=take;need-=take}}r.scaled=true;r.scaledAt=new Date().toISOString();save();toast("Ricetta scalata dal magazzino")}
$("#backupBtn").onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mastro_shayen_backup.json";a.click();URL.revokeObjectURL(a.href)};
$("#restoreFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(!x.items||!x.recipes)throw 0;if(confirm("Sostituire i dati attuali con il backup?")){data=x;save();toast("Backup caricato")}}catch{alert("Backup non valido")}};rd.readAsText(f)};
$$("[data-reset]").forEach(b=>b.onclick=()=>{const c=b.dataset.reset;if(confirm("Reset del reparto "+c+"?")){data.items=data.items.filter(i=>i.category!==c);save();toast("Reparto resettato")}});
$("#resetAll").onclick=()=>{if(confirm("ATTENZIONE: eliminare TUTTO il magazzino e tutte le ricette?")){data={items:[],recipes:[]};save();toast("Dati azzerati")}};
const dl=document.createElement("datalist");dl.id="materials";dl.innerHTML=grouped().map(x=>`<option value="${esc(x.name)}">`).join("");document.body.appendChild(dl);
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});
renderAll();
