const KEY="mastro_shayen_magazzino_v1";
let data=JSON.parse(localStorage.getItem(KEY)||'{"items":[],"recipes":[]}');
data.items=data.items||[]; data.recipes=data.recipes||[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const categories=["Malti","Luppoli","Lieviti","Additivi"];
const icons={Malti:"🌾",Luppoli:"🌿",Lieviti:"🧫",Additivi:"🧪"};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
data.items.forEach(i=>{if(!i.id)i.id=uid()});
data.recipes.forEach(r=>{if(!r.id)r.id=uid(); if(!r.status)r.status="active"});
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2400)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function openModal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden");document.body.style.overflow="hidden";bindSwipeDelete()}
function closeModal(){$("#modal").classList.add("hidden");document.body.style.overflow=""}
$("#modalClose").onclick=closeModal;
function showView(v){$$('.view').forEach(x=>x.classList.remove('active'));$("#"+v).classList.add('active');$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo(0,0)}
$$('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$("#settingsBtn").onclick=()=>showView("settings"); $("#closeSettings").onclick=()=>showView("dashboard");
function dateState(d){if(!d)return"";const now=new Date(),x=new Date(d+"T23:59:59"),days=(x-now)/86400000;if(days<0)return"expired";if(days<=30)return"warning";return""}
function grouped(){const map={};data.items.forEach((i,idx)=>{const key=(i.category+"|"+String(i.name||'').trim()).toLowerCase();if(!map[key])map[key]={name:String(i.name||'').trim(),category:i.category,total:0,unit:i.unit,lots:[]};map[key].total+=Number(i.qty)||0;map[key].lots.push({...i,__index:idx})});return Object.values(map)}
function renderDashboard(){renderInventory()}
function renderInventory(){
 const q=$("#inventorySearch").value.toLowerCase(), c=$("#categoryFilter").value;
 const groups=grouped().filter(g=>(!q||g.name.toLowerCase().includes(q))&&(!c||g.category===c));
 if(!groups.length){$("#inventoryList").innerHTML='<div class="empty">Nessun materiale trovato.</div>';return}
 const html=!c?categories.map(category=>{const items=groups.filter(g=>g.category===category);if(!items.length)return"";return `<section class="inventory-section"><h2 class="inventory-section-title">${icons[category]} ${category}</h2><div class="inventory-section-list">${items.map(inventoryGroupHTML).join("")}</div></section>`}).join(""):groups.map(inventoryGroupHTML).join("");
 $("#inventoryList").innerHTML=html;
 $$(".inventory-clickable").forEach(el=>bindInventoryCard(el));
}
function bindInventoryCard(el){let sx=0,moved=false;el.onclick=()=>{if(!moved)editGroup(decodeURIComponent(el.dataset.name),el.dataset.category);moved=false};el.addEventListener('touchstart',e=>{sx=e.touches[0].clientX;moved=false},{passive:true});el.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(dx<-70){moved=true;el.classList.add('swiped')}else if(dx>30){moved=true;el.classList.remove('swiped')}},{passive:true});el.querySelector('.inventory-delete').onclick=e=>{e.stopPropagation();const n=decodeURIComponent(el.dataset.name),cat=el.dataset.category;if(confirm('Rimuovi dal magazzino?')){data.items=data.items.filter(i=>!(i.category===cat&&String(i.name||'').trim().toLowerCase()===n.trim().toLowerCase()));save();toast('Articolo rimosso')}}}
function inventoryGroupHTML(g){return `<article class="material-card inventory-clickable" data-name="${encodeURIComponent(g.name)}" data-category="${esc(g.category)}"><button type="button" class="inventory-delete" aria-label="Rimuovi">×</button><div class="material-main"><div><div class="material-name">${esc(g.name)}</div><div class="material-meta">${esc(g.category)} · ${g.lots.length} lotto${g.lots.length===1?'':'i'}</div></div><div class="material-total">${g.total} ${esc(g.unit||g.lots[0]?.unit||'')}</div></div><details class="material-details-wrap" onclick="event.stopPropagation()"><summary>Dettaglio lotti</summary><div class="material-details">${g.lots.map(l=>`<div class="lot"><span>${esc(l.expiry||'Nessuna scadenza')} ${dateState(l.expiry)==='expired'?'<span class="lot-expired">SCADUTO</span>':dateState(l.expiry)==='warning'?'<span class="lot-warning">IN SCADENZA</span>':''}</span><b>${l.qty} ${esc(l.unit)}</b></div>`).join('')}</div></details></article>`}
function editGroup(name,category){const idxs=data.items.map((x,i)=>({x,i})).filter(o=>o.x.category===category&&String(o.x.name||'').trim().toLowerCase()===name.trim().toLowerCase()).map(o=>o.i);if(!idxs.length)return;openModal(`<form id="itemEditor" class="form"><h2>Modifica ${esc(name)}</h2><label>Nome materiale<input name="name" value="${esc(data.items[idxs[0]].name)}" required></label><label>Categoria<select name="category">${categories.map(c=>`<option ${c===category?'selected':''}>${c}</option>`).join('')}</select></label><div id="lotEditorList" class="lot-editor-list">${idxs.map((i,n)=>lotEditorRow(data.items[i],n)).join('')}</div><button type="button" class="secondary" id="addLotEdit">＋ Aggiungi lotto</button><div class="editor-actions"><button type="button" class="danger" id="deleteItem">🗑 Rimuovi dal magazzino</button><button class="primary">Salva modifiche</button></div></form>`);$("#addLotEdit").onclick=()=>{$("#lotEditorList").insertAdjacentHTML('beforeend',lotEditorRow({name:name,category:category,qty:0,unit:data.items[idxs[0]].unit||'kg',expiry:''},$$('.lot-editor-row').length))};$("#itemEditor").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),newName=fd.get('name').trim(),newCat=fd.get('category');const rows=$$('.lot-editor-row');const replacement=rows.map(row=>({id:uid(),name:newName,category:newCat,qty:Number(row.querySelector('[name="qty"]').value)||0,unit:row.querySelector('[name="unit"]').value,expiry:row.querySelector('[name="expiry"]').value||''}));idxs.sort((a,b)=>b-a).forEach(i=>data.items.splice(i,1));data.items.push(...replacement);save();closeModal();toast('Articolo aggiornato')};$("#deleteItem").onclick=()=>{if(confirm('Rimuovi dal magazzino?')){idxs.sort((a,b)=>b-a).forEach(i=>data.items.splice(i,1));save();closeModal();toast('Articolo rimosso')}}}
function lotEditorRow(l,n){return `<div class="lot-editor-row swipe-delete"><label>Quantità<input name="qty" type="number" step="any" value="${esc(l.qty)}"></label><label>Unità<select name="unit">${['kg','g','L','ml','pz'].map(u=>`<option ${u===l.unit?'selected':''}>${u}</option>`).join('')}</select></label><label>Scadenza<input name="expiry" type="date" value="${esc(l.expiry||'')}"></label><button type="button" class="row-delete" aria-label="Rimuovi lotto">×</button></div>`}
function bindSwipeDelete(){$$('.swipe-delete').forEach(row=>{let sx=0;row.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});row.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(dx<-70)row.classList.add('swiped');else if(dx>30)row.classList.remove('swiped')},{passive:true});row.querySelector('.row-delete')?.addEventListener('click',()=>{if(confirm('Rimuovi questo lotto?'))row.remove()})})}
$("#inventorySearch").oninput=renderInventory;$("#categoryFilter").onchange=renderInventory;
function openAddMaterial(){openModal(`<form id="addItemForm" class="form"><h2>Aggiungi materiale</h2><label>Nome materiale<input name="name" required placeholder="es. Maris Otter"></label><label>Categoria<select name="category" class="shayen-select">${categories.map(c=>`<option>${c}</option>`).join('')}</select></label><div class="form-grid"><label>Quantità<input name="qty" type="number" step="any" required></label><label>Unità<select name="unit" class="shayen-select"><option>kg</option><option>g</option><option>L</option><option>ml</option><option>pz</option></select></label></div><label>Scadenza<input name="expiry" type="date"></label><div class="editor-actions"><button type="submit" class="primary">Aggiungi al magazzino</button></div></form>`)}
$(document).on('submit','#addItemForm',e=>{e.preventDefault();const f=new FormData(e.target);data.items.push({id:uid(),name:f.get('name').trim(),category:f.get('category'),qty:Number(f.get('qty'))||0,unit:f.get('unit'),expiry:f.get('expiry')||''});save();closeModal();toast('Materiale aggiunto')});
function creatorAnalysis(){const totals={};grouped().forEach(g=>totals[g.category]=(totals[g.category]||0)+g.total);const maltKg=totals.Malti||0,hopsG=totals.Luppoli||0,yeast=totals.Lieviti||0,litresByMalt=maltKg>0?Math.floor(maltKg/.22*10)/10:0,litresByHops=hopsG>0?Math.floor(hopsG/5):0,litres=Math.max(0,Math.min(litresByMalt||999,litresByHops||999));return litres>0&&yeast>0?[['Pale Ale',litres,'Stima locale'],['IPA',Math.max(0,Math.floor(litres*.75*10)/10),'Stima locale'],['Session Ale',Math.max(0,Math.floor(litres*1.2*10)/10),'Stima locale']]:[['Analisi incompleta',0,'Servono malti, luppoli e lievito']]} 
function renderCreator(){$("#creatorResult").innerHTML=creatorAnalysis().map(x=>`<article class="creator-card"><div><strong>${x[0]}</strong><small>${esc(x[2])}</small></div><b>${x[1]} L</b></article>`).join('')}
$("#creatorAnalyze").onclick=renderCreator;
$("#creatorQuestion").onsubmit=e=>{e.preventDefault();const q=$("#creatorInput").value.trim();if(!q)return;const a=creatorAnalysis();$("#creatorChat").insertAdjacentHTML('beforeend',`<div class="chat-user">${esc(q)}</div><div class="chat-ai">In questa versione Creator usa i dati del magazzino per l'analisi locale: ${a.map(x=>`${x[0]} ${x[1]} L`).join(', ')}.</div>`);$("#creatorInput").value=''};
function unitBase(q,u){q=Number(q)||0;if(['kg','g'].includes(u))return {v:u==='kg'?q*1000:q,t:'g'};if(['L','ml'].includes(u))return {v:u==='L'?q*1000:q,t:'ml'};return {v:q,t:'pz'}}
function fromBase(v,u){if(u==='kg')return v/1000;if(u==='L')return v/1000;return v}
function availableFor(name,category){return data.items.filter(i=>i.category===category&&String(i.name||'').trim().toLowerCase()===String(name||'').trim().toLowerCase()).reduce((s,i)=>s+unitBase(i.qty,i.unit).v,0)}
function recipeForm(r=null){const ingredients=r?.ingredients?.length?r.ingredients:[{category:'Malti',name:'',qty:0,unit:'kg'}];openModal(`<form id="recipeEditor" class="form"><h2>${r?'Modifica ricetta':'Nuova ricetta'}</h2><label>Nome ricetta<input name="recipeName" value="${esc(r?.name||'')}" required placeholder="es. American IPA"></label><label>Stile<input name="style" value="${esc(r?.style||'')}" placeholder="es. IPA"></label><label>Volume previsto (L)<input name="volume" type="number" step="0.1" value="${esc(r?.volume||20)}" required></label><div class="ingredient-section"><div class="ingredient-section-head"><h3>Materie prime</h3><span class="section-icon">🍺</span></div><div id="recipeIngredients" class="ingredient-table">${ingredients.map(recipeIngredientRow).join('')}</div><button type="button" class="add-row" id="addIngredient">＋ Aggiungi prodotto</button></div><div class="editor-actions"><button type="button" class="secondary" id="cancelRecipe">Annulla</button><button class="primary">Salva ricetta</button></div></form>`);$("#addIngredient").onclick=()=>{$("#recipeIngredients").insertAdjacentHTML('beforeend',recipeIngredientRow({category:'Malti',name:'',qty:0,unit:'kg'}));bindRecipeRows()};$("#cancelRecipe").onclick=closeModal;bindRecipeRows();function bindRecipeRows(){$$('.remove-ing').forEach(b=>b.onclick=()=>b.parentElement.remove())}$("#recipeEditor").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),rows=$$('.ingredient-row');const ings=rows.map(row=>({category:row.querySelector('[name="category"]').value,name:row.querySelector('[name="ingredient"]').value,qty:Number(row.querySelector('[name="qty"]').value)||0,unit:row.querySelector('[name="unit"]').value})).filter(x=>x.name&&x.qty>0);if(!ings.length){toast('Aggiungi almeno una materia prima');return}const rec={id:r?.id||uid(),name:f.get('recipeName').trim(),style:f.get('style').trim(),volume:Number(f.get('volume'))||0,ingredients:ings,status:r?.status||'active',createdAt:r?.createdAt||Date.now(),scaledDeltas:r?.scaledDeltas||[]};if(r){const i=data.recipes.findIndex(x=>x.id===r.id);if(i>=0)data.recipes[i]=rec}else data.recipes.push(rec);save();closeModal();toast('Ricetta salvata')}}
function recipeIngredientRow(i){const opts=data.items.filter((x,idx,a)=>a.findIndex(y=>y.category===x.category&&String(y.name).trim().toLowerCase()===String(x.name).trim().toLowerCase())===idx).filter(x=>x.category===i.category);return `<div class="ingredient-row"><select name="category" class="recipe-cat">${categories.map(c=>`<option ${c===i.category?'selected':''}>${c}</option>`).join('')}</select><select name="ingredient" class="recipe-ing"><option value="">Prodotto</option>${opts.map(x=>`<option ${x.name===i.name?'selected':''}>${esc(x.name)}</option>`).join('')}</select><input name="qty" type="number" step="any" value="${esc(i.qty||0)}" placeholder="Qtà"><select name="unit"><option ${i.unit==='kg'?'selected':''}>kg</option><option ${i.unit==='g'?'selected':''}>g</option><option ${i.unit==='L'?'selected':''}>L</option><option ${i.unit==='ml'?'selected':''}>ml</option><option ${i.unit==='pz'?'selected':''}>pz</option></select><button type="button" class="remove-ing">×</button></div>`}
function renderRecipes(){const active=data.recipes.filter(r=>r.status!=='archived'),arch=data.recipes.filter(r=>r.status==='archived');const el=$("#recipeList");if(window.recipeArchiveOpen){$("#recipeArchiveBtn").textContent='← Ricette';el.innerHTML=arch.length?arch.map(archivedRecipeCard).join(''):'<div class="empty">nessuna ricetta archiviata al momento</div>'}else{$("#recipeArchiveBtn").textContent=`Archiviate${arch.length?` (${arch.length})`:''}`;el.innerHTML=active.length?active.map(recipeCard).join(''):'<div class="empty">Nessuna ricetta. Crea la tua prima ricetta.</div>'}bindRecipeCards()}
function ingredientLines(r){return (r.ingredients||[]).map(i=>`<div class="ingredient-line"><span>${esc(i.name)} <small>${esc(i.category)}</small></span><b>${i.qty} ${esc(i.unit)}</b></div>`).join('')}
function recipeCard(r){return `<article class="recipe-card"><div class="recipe-title">${esc(r.name)}</div><div class="recipe-style">${esc(r.style||'Stile non indicato')} · ${r.volume} L</div><div class="recipe-section"><h4>Materie prime</h4>${ingredientLines(r)}</div><div class="recipe-actions"><button class="secondary edit-recipe" data-id="${r.id}">Modifica</button><button class="primary scale-recipe" data-id="${r.id}">SCALA DAL MAGAZZINO</button></div></article>`}
function archivedRecipeCard(r){return `<article class="recipe-card archived-card swipe-delete-recipe" data-id="${r.id}"><div class="recipe-title">${esc(r.name)}</div><div class="recipe-style">${esc(r.style||'Stile non indicato')} · ${r.volume} L</div><div class="recipe-section"><h4>Materie prime</h4>${ingredientLines(r)}</div><div class="recipe-actions"><button class="secondary restore-recipe" data-id="${r.id}">Ripristina</button><button class="danger delete-recipe" data-id="${r.id}">× Elimina definitivamente</button></div></article>`}
function bindRecipeCards(){$$('.edit-recipe').forEach(b=>b.onclick=()=>recipeForm(data.recipes.find(r=>r.id===b.dataset.id)));$$('.scale-recipe').forEach(b=>b.onclick=()=>scaleRecipe(b.dataset.id));$$('.restore-recipe').forEach(b=>b.onclick=()=>restoreRecipe(b.dataset.id));$$('.delete-recipe').forEach(b=>b.onclick=()=>deleteRecipe(b.dataset.id));$$('.swipe-delete-recipe').forEach(card=>{let sx=0;card.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});card.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(dx<-70)card.classList.add('swiped');else if(dx>30)card.classList.remove('swiped')},{passive:true})})}
function scaleRecipe(id){const r=data.recipes.find(x=>x.id===id);if(!r)return;const need=new Map();(r.ingredients||[]).forEach(i=>{const k=i.category+'|'+i.name.toLowerCase().trim();const b=unitBase(i.qty,i.unit);need.set(k,(need.get(k)||0)+b.v)});for(const [k,qty] of need){const [cat,name]=k.split('|');if(availableFor(name,cat)<qty){toast(`Quantità insufficiente: ${name}`);return}}const deltas=[];for(const [k,qty] of need){const [cat,name]=k.split('|');let remain=qty;const lots=data.items.filter(i=>i.category===cat&&String(i.name||'').trim().toLowerCase()===name).sort((a,b)=>(a.expiry||'9999').localeCompare(b.expiry||'9999'));for(const lot of lots){if(remain<=0)break;const cap=unitBase(lot.qty,lot.unit).v;const take=Math.min(cap,remain);lot.qty=Number((lot.qty-fromBase(take,lot.unit)).toFixed(6));remain-=take;deltas.push({itemId:lot.id,qtyBase:take,unit:lot.unit,snapshot:{name:lot.name,category:lot.category,unit:lot.unit,expiry:lot.expiry}})}}r.status='archived';r.scaledDeltas=deltas;r.archivedAt=Date.now();save();toast('Ricetta archiviata e materie prime scalate dal magazzino')}
function restoreRecipe(id){const r=data.recipes.find(x=>x.id===id);if(!r)return;(r.scaledDeltas||[]).forEach(d=>{let lot=data.items.find(i=>i.id===d.itemId);if(lot)lot.qty=Number((lot.qty+fromBase(d.qtyBase,lot.unit)).toFixed(6));else data.items.push({id:d.itemId,...d.snapshot,qty:fromBase(d.qtyBase,d.unit)})});r.status='active';r.scaledDeltas=[];save();toast('Ricetta ripristinata e quantità reintegrate')}
function deleteRecipe(id){if(confirm('Eliminare definitivamente questa ricetta?')){data.recipes=data.recipes.filter(r=>r.id!==id);save();toast('Ricetta eliminata definitivamente')}}
window.recipeArchiveOpen=false;
$("#newRecipe")?.addEventListener('click',()=>recipeForm());
$("#recipeArchiveBtn")?.addEventListener('click',()=>{window.recipeArchiveOpen=!window.recipeArchiveOpen;renderRecipes()});
$("#addProduct")?.addEventListener('click',()=>openAddMaterial());
$("#backupBtn").onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mastro_shayen_backup.json';a.click();URL.revokeObjectURL(a.href)};
$("#restoreFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(!x.items||!x.recipes)throw 0;if(confirm('Sostituire i dati attuali con il backup?')){data=x;data.items.forEach(i=>{if(!i.id)i.id=uid()});data.recipes.forEach(r=>{if(!r.id)r.id=uid();if(!r.status)r.status='active'});save();toast('Backup caricato')}}catch{alert('Backup non valido')}};rd.readAsText(f)};
$$('[data-reset]').forEach(b=>b.onclick=()=>{const c=b.dataset.reset;if(confirm('Reset del reparto '+c+'?')){data.items=data.items.filter(i=>i.category!==c);save();toast('Reparto resettato')}});
$("#resetAll").onclick=()=>{if(confirm('ATTENZIONE: eliminare TUTTO il magazzino e tutte le ricette?')){data={items:[],recipes:[]};save();toast('Dati azzerati')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
function renderAll(){renderDashboard();renderRecipes();renderCreator()}renderAll();
